---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./dev;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties.hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      jdbc.lob.non_contextual_creation: true
      temp.use_jdbc_metadata_defaults: false
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: prod
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./prod;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      jdbc.lob.non_contextual_creation: true
      temp.use_jdbc_metadata_defaults: false
server:
  port: 8081